apiVersion: v1
kind: Service
metadata:
  name: mynginx-svc
  labels:
    app: mynginx
spec:
   type: NodePort
   ports:
   - port: 80
     nodeport: 30001
     protocol: TCP
   selector:
      app: mynginx
       
 